"use client";

import React, { useState, useRef } from "react";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Trash2,
  FileJson,
  Upload,
  AlertCircle,
  FileText,
  Settings,
} from "lucide-react";
import { cn } from "@/lib";

const SAMPLE_JSON = `{

  "reportTitle": "Quarterly Sales Report",
  "date": "2023-10-25",
  "department": "Sales",
  "items": [
    { "product": "Widget A", "quantity": 120, "price": 25.00 },
    { "product": "Widget B", "quantity": 85, "price": 35.50 },
    { "product": "Widget C", "quantity": 200, "price": 15.75 }
  ],
  "summary": {
    "totalItems": 405,
    "revenue": 9567.50,
    "status": "Exceeded Targets"
  }
}`;

/* eslint-disable @typescript-eslint/no-explicit-any */
export default function JsonToPdfConverterTool() {
  const [input, setInput] = useState("");
  const [error, setError] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // PDF Settings
  const [title, setTitle] = useState("My Document");
  const [pageSize, setPageSize] = useState("a4");
  const [orientation, setOrientation] = useState("portrait");
  const [fontSize, setFontSize] = useState(12);
  const [useTable, setUseTable] = useState(true);
  const [prettyPrint, setPrettyPrint] = useState(false);
  const [showPageNumbers, setShowPageNumbers] = useState(true);
  const [addHeaderFooter, setAddHeaderFooter] = useState(true);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      const text = event.target?.result as string;
      setInput(text);
      setError(null);
    };
    reader.readAsText(file);
  };

  const loadSample = () => {
    setInput(SAMPLE_JSON);
    setError(null);
  };

  const handleConvert = async () => {
    setError(null);
    if (!input.trim()) {
      setError("Please enter some JSON to convert.");
      return;
    }

    let parsedData: any;
    try {
      parsedData = JSON.parse(input);
    } catch (e) {
      console.error(e);
      setError("Invalid JSON format. Please check your syntax.");
      return;
    }

    try {
      const { default: jsPDF } = await import("jspdf");
      const { default: autoTable } = await import("jspdf-autotable");

      const doc = new jsPDF({
        orientation: orientation as "portrait" | "landscape",
        unit: "pt",
        format: pageSize,
      });

      doc.setFontSize(fontSize);
      const margin = 40;
      let yPos = margin;

      if (addHeaderFooter) {
        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text("Generated by RhythmiqCX JSON to PDF Converter", margin, 20);
        doc.setFontSize(fontSize);
        doc.setTextColor(0);
      }

      if (title) {
        doc.setFontSize(fontSize + 6);
        doc.setFont("helvetica", "bold");
        doc.text(title, margin, yPos + 20);
        yPos += 40;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(fontSize);
      }

      const renderTable = (
        header: string | null,
        data: any,
        startY: number,
      ) => {
        let finalY = startY;

        // 1. Add Header if provided
        if (header) {
          doc.setFontSize(14);
          doc.setFont("helvetica", "bold");
          doc.text(
            header.charAt(0).toUpperCase() + header.slice(1),
            margin,
            finalY,
          );
          finalY += 20;
          doc.setFont("helvetica", "normal");
          doc.setFontSize(fontSize);
        }

        // 2. Prepare Data for Table
        let tableBody: any[] = [];
        let tableHead: string[][] = [];

        if (Array.isArray(data)) {
          if (data.length > 0) {
            // Check if array of objects or primitives
            if (typeof data[0] === "object" && data[0] !== null) {
              // Array of Objects
              const allKeys = Array.from(
                new Set(data.flatMap((item: any) => Object.keys(item || {}))),
              );
              tableHead = [allKeys];
              tableBody = data.map((item: any) =>
                allKeys.map((key) => {
                  const val = item?.[key];
                  if (Array.isArray(val)) return val.join(", ");
                  if (typeof val === "object" && val !== null)
                    return JSON.stringify(val);
                  return String(val ?? "");
                }),
              );
            } else {
              // Array of Primitives
              tableHead = [["Value"]];
              tableBody = data.map((item) => [String(item)]);
            }
          } else {
            // Empty array
            doc.setFontSize(10);
            doc.setTextColor(100);
            doc.text("(Empty List)", margin, finalY);
            return finalY + 15;
          }
        } else if (typeof data === "object" && data !== null) {
          // Single Object -> Key-Value Table
          tableHead = [["Key", "Value"]];
          tableBody = Object.entries(data).map(([k, v]) => {
            let displayVal = "";
            if (Array.isArray(v)) displayVal = v.join(", ");
            else if (typeof v === "object" && v !== null)
              displayVal = JSON.stringify(v);
            else displayVal = String(v ?? "");
            return [k, displayVal];
          });
        } else {
          // Primitive value passed (edge case)
          doc.text(String(data), margin, finalY);
          return finalY + 15;
        }

        // 3. Render Table
        autoTable(doc, {
          startY: finalY,
          head: tableHead,
          body: tableBody,
          margin: { top: margin, bottom: margin, left: margin, right: margin },
          theme: "grid",
          styles: { fontSize: fontSize, cellPadding: 4 },
          headStyles: { fillColor: [66, 66, 66] },
          // Handle page break
          pageBreak: "auto",
        });

        // @ts-expect-error - jspdf-autotable adds lastAutoTable to doc
        return (doc.lastAutoTable?.finalY || finalY) + 30; // Add padding for next section
      };

      if (useTable) {
        if (Array.isArray(parsedData)) {
          // Root is Array -> Single Table
          yPos = renderTable(null, parsedData, yPos);
        } else if (typeof parsedData === "object" && parsedData !== null) {
          // Root is Object -> Iterate keys
          // Strategy:
          // 1. Collect primitives for a "Summary" section at top?
          // 2. Or just iterate all keys in order.
          // Let's iterate keys to respect order, grouping primitives if possible?
          // Simpler: Just iterate each key. If primitive, add to a "General" list. If complex, render table.

          const primitives: [string, any][] = [];
          const complex: [string, any][] = [];

          Object.entries(parsedData).forEach(([k, v]) => {
            if (typeof v === "object" && v !== null) {
              complex.push([k, v]);
            } else {
              primitives.push([k, v]);
            }
          });

          // Render Primitives (General Info)
          if (primitives.length > 0) {
            doc.setFontSize(14);
            doc.setFont("helvetica", "bold");
            doc.text("General Info", margin, yPos);
            yPos += 20;
            doc.setFont("helvetica", "normal");
            doc.setFontSize(fontSize);

            const primObj = Object.fromEntries(primitives);
            yPos = renderTable(null, primObj, yPos);
          }

          // Render Complex (Arrays/Objects)
          complex.forEach(([k, v]) => {
            // Check if we need a new page? autoTable handles it usually, but headers logic calls text() directly.
            // Simple check: if yPos > page height - 100, add page.
            if (yPos > doc.internal.pageSize.getHeight() - 100) {
              doc.addPage();
              yPos = margin + 20;
            }
            yPos = renderTable(k, v, yPos);
          });
        } else {
          // Root is Primitive
          doc.text(String(parsedData), margin, yPos);
        }
      } else {
        const textContent = prettyPrint
          ? JSON.stringify(parsedData, null, 2)
          : JSON.stringify(parsedData);

        const splitText = doc.splitTextToSize(
          textContent,
          doc.internal.pageSize.getWidth() - 2 * margin,
        );

        doc.text(splitText, margin, yPos);
      }

      if (addHeaderFooter || showPageNumbers) {
        const pageCount = doc.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
          doc.setPage(i);
          doc.setFontSize(10);
          doc.setTextColor(150);

          const footerText = [];
          if (addHeaderFooter)
            footerText.push(`Generated on ${new Date().toLocaleDateString()}`);
          if (showPageNumbers) footerText.push(`Page ${i} of ${pageCount}`);

          doc.text(
            footerText.join(" | "),
            doc.internal.pageSize.getWidth() / 2,
            doc.internal.pageSize.getHeight() - 20,
            { align: "center" },
          );
        }
      }

      doc.save(
        `${title.replace(/[^a-z0-9]/gi, "_").toLowerCase() || "document"}.pdf`,
      );
    } catch (e: any) {
      console.error(e);
      if (
        e.message?.includes("jspdf") ||
        e.message?.includes("Cannot find module")
      ) {
        setError(
          "Dependencies missing. Please install 'jspdf' and 'jspdf-autotable' in your project.",
        );
      } else {
        setError("Failed to generate PDF. Check console for details.");
      }
    }
  };

  return (
    <div className="flex flex-col gap-8 w-full">
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Input Section - Spans 2 columns on large screens */}
        <div className="lg:col-span-2 flex flex-col gap-4 h-[600px]">
          <div className="flex items-center justify-between">
            <Label className="text-base font-semibold flex items-center gap-2">
              <FileJson className="w-5 h-5 text-yellow-500" />
              Input JSON
            </Label>
            <div className="flex gap-2">
              <input
                type="file"
                ref={fileInputRef}
                className="hidden"
                accept=".json"
                onChange={handleFileUpload}
              />
              <Button
                variant="outline"
                size="sm"
                onClick={() => fileInputRef.current?.click()}
              >
                <Upload className="w-4 h-4 mr-2" />
                Upload File
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setInput("")}
                className="text-muted-foreground hover:text-destructive"
              >
                <Trash2 className="w-4 h-4 mr-2" />
                Clear
              </Button>
              <Button variant="secondary" size="sm" onClick={loadSample}>
                Load Sample
              </Button>
            </div>
          </div>

          <div
            className={cn(
              "relative flex-1 rounded-xl border-2 transition-all bg-card overflow-hidden",
              error
                ? "border-destructive/50"
                : "border-border hover:border-border/80 focus-within:border-primary/50",
            )}
          >
            <textarea
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Paste your JSON here..."
              className="w-full h-full p-4 md:p-6 bg-transparent resize-none focus:outline-none font-mono text-sm leading-relaxed scrollbar-thin scrollbar-thumb-border scrollbar-track-transparent"
              spellCheck={false}
            />
          </div>
          {error && (
            <div className="flex items-center gap-2 text-destructive text-sm font-medium animate-in slide-in-from-top-2 fade-in bg-destructive/10 p-3 rounded-lg border border-destructive/20">
              <AlertCircle className="w-4 h-4" />
              {error}
            </div>
          )}
        </div>

        {/* Settings Section */}
        <div className="flex flex-col gap-6 h-full">
          <div className="flex items-center gap-2 pb-2 border-b border-border/50">
            <Settings className="w-5 h-5 text-primary" />
            <h2 className="text-lg font-semibold">PDF Settings</h2>
          </div>

          <div className="space-y-4">
            <div className="space-y-2">
              <Label>Document Title</Label>
              <Input
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="Report Title"
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>Page Size</Label>
                <Select value={pageSize} onValueChange={setPageSize}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="a4">A4</SelectItem>
                    <SelectItem value="letter">Letter</SelectItem>
                    <SelectItem value="legal">Legal</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>Orientation</Label>
                <Select value={orientation} onValueChange={setOrientation}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="portrait">Portrait</SelectItem>
                    <SelectItem value="landscape">Landscape</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div className="space-y-2">
              <Label>Font Size (pt)</Label>
              <Input
                type="number"
                min={8}
                max={24}
                value={fontSize}
                onChange={(e) => setFontSize(Number(e.target.value))}
              />
            </div>

            <div className="space-y-4 pt-2">
              <div className="flex items-center justify-between">
                <Label className="cursor-pointer" htmlFor="table-fmt">
                  Table Formatting
                </Label>
                <Switch
                  id="table-fmt"
                  checked={useTable}
                  onCheckedChange={setUseTable}
                />
              </div>
              <div className="flex items-center justify-between">
                <Label className="cursor-pointer" htmlFor="pretty-print">
                  Pretty Print JSON
                </Label>
                <Switch
                  id="pretty-print"
                  checked={prettyPrint}
                  onCheckedChange={setPrettyPrint}
                />
              </div>
              <div className="flex items-center justify-between">
                <Label className="cursor-pointer" htmlFor="page-nums">
                  Page Numbers
                </Label>
                <Switch
                  id="page-nums"
                  checked={showPageNumbers}
                  onCheckedChange={setShowPageNumbers}
                />
              </div>
              <div className="flex items-center justify-between">
                <Label className="cursor-pointer" htmlFor="meta-info">
                  Header & Footer
                </Label>
                <Switch
                  id="meta-info"
                  checked={addHeaderFooter}
                  onCheckedChange={setAddHeaderFooter}
                />
              </div>
            </div>
          </div>

          <div className="mt-auto pt-6">
            <Button
              size="lg"
              className="w-full bg-primary hover:bg-primary/90 shadow-lg shadow-primary/20 text-lg py-6"
              onClick={handleConvert}
            >
              <FileText className="w-5 h-5 mr-2" />
              Convert to PDF
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
